### ISSUE TITLE
Fix the meta tag for the subscribe page

### ISSUE THREAD

**Issue by athishsreeram** [HackerNewsIndia/diaryblogadminui#1]
https://diaryblog.connectingpeopletech.com/661a51acb8a5cd579f5d69ce/subscribe 

https://diaryblog.connectingpeopletech.com/650053ad0abf74664d046ca6/viewposts

![IMG_0713](https://github.com/HackerNewsIndia/diaryblogadminui/assets/29419776/1dcdb960-fa39-4996-8d36-a2f65a66b731)

**Comment by VinothManickam** [comment]
![Capture126](https://github.com/HackerNewsIndia/diaryblogadminui/assets/103953710/2450a8b8-033a-443a-9772-3085b7246c87)
