### ISSUE TITLE
Fix the total follower count 

### ISSUE THREAD

**Issue by athishsreeram** [HackerNewsIndia/diaryblogadminui#3]
Fix the total follower count 

![IMG_0717](https://github.com/HackerNewsIndia/diaryblogadminui/assets/29419776/e7c6586a-d7a5-4809-a45e-0600bf24218d)

**Comment by VinothManickam** [comment]
![Capture110](https://github.com/HackerNewsIndia/diaryblogadminui/assets/103953710/6b47956d-16e5-4609-9581-05edf9625818)

**Comment by athishsreeram** [comment]
This was root cause 
![IMG-20240416-WA0001](https://github.com/HackerNewsIndia/diaryblogadminui/assets/29419776/0730559e-628c-493b-a633-43d2a9c48c88)

**Comment by athishsreeram** [comment]
This issue is fixed by @VinothManickam
