### ISSUE TITLE
Recently Posted In Dashboard Fix size of the cards 

### ISSUE THREAD

**Issue by athishsreeram** [HackerNewsIndia/diaryblogadminui#4]
Image make it very uneven look an feel figure out a solution to make it look good at UI identical

**Comment by VinothManickam** [comment]
![Uploading Capture125.PNG…]()

**Comment by VinothManickam** [comment]
![Capture125](https://github.com/HackerNewsIndia/diaryblogadminui/assets/103953710/6073952e-dccd-4126-8a99-19e408df1bca)
