### ISSUE TITLE
After Updated success \ Created successfully hide the form and show back to button in the middle

### ISSUE THREAD

**Issue by athishsreeram** [HackerNewsIndia/diaryblogadminui#6]
<img width="1366" alt="image" src="https://github.com/HackerNewsIndia/diaryblogadminui/assets/29419776/0e644969-33d8-4200-a025-48263b9a4316">

**Comment by VinothManickam** [comment]
![Uploading Capture124.PNG…]()

**Comment by VinothManickam** [comment]
![Capture124](https://github.com/HackerNewsIndia/diaryblogadminui/assets/103953710/92bc922a-9ff4-423c-bbec-5d7296ed11b3)
