### ISSUE TITLE
Add preview image in Create post image 

### ISSUE THREAD

**Issue by athishsreeram** [HackerNewsIndia/diaryblogadminui#7]
<img width="1134" alt="image" src="https://github.com/HackerNewsIndia/diaryblogadminui/assets/29419776/2c0fbdbb-626d-435a-983a-bb6d6d715e04">

**Comment by VinothManickam** [comment]
![Capture128](https://github.com/HackerNewsIndia/diaryblogadminui/assets/103953710/e7c799bc-eccd-477c-8d56-3ca49f6d42bc)
